version: '3.8'

services:
  postgres:
    container_name: tests-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tests
      PGDATA: /data/postgres
    volumes:
      - ./.docker/pg:/data/postgres
